- name: Run SSH command
  uses: appleboy/ssh-action@v1.0.3
  with:
    HOST: ${{ secrets.SSH_HOST }}
    USERNAME: ${{ secrets.SSH_USERNAME }}
    PASSWORD: ${{ secrets.SSH_PASSWORD }}
    PORT: ${{ secrets.SSH_PORT }}
    SCRIPT: "echo 'Hello, world!'"

    name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run playbook on ansible server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}
        script: ansible-playbook /opt/argo.yaml
